// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';

// Note: Standard Prisma configuration is in schema.prisma
// The seed command is configured in package.json under "prisma.seed"
// This file is optional and can be removed if not needed for custom configuration.
