export const MIDDLEWARE_MATCHER = [
  '/',
  '/register',
  '/login',
  '/signup',
  '/forgot-password',
  '/dashboard',
  '/dashboard/:path*',
  '/users',
  '/users/:path*',
  '/permissions',
  '/permissions/:path*',
  '/leads',
  '/leads/:path*',
  '/tasks',
  '/tasks/:path*',
  '/reports',
  '/reports/:path*',
  '/audit',
  '/audit/:path*',
  '/settings',
  '/settings/:path*',
  '/portal',
  '/portal/:path*',
] as const;
